spring:
  data:
    mongodb:
      uri: ${MONGODB_URL:mongodb://localhost:27017/orderNumbersDB}
      #uri: mongodb://localhost:27017/orderNumbersDB
  application:
    name: "numberGenerateService"
server:
  port: 8091